// Libellés du reçu A5 (lib/utils/pdf.ts) depuis next-intl — UNE seule liste,
// partagée par Nouvelle vente et l'Historique : la liste de l'historique
// était incomplète, et le PDF retombait sur l'anglais pour « SALES RECEIPT »,
// « Payment method », « PAID », « Amount paid », « Generated by ».
export function receiptLabelsFromT(t: (key: string) => string) {
  return {
    receipt: t('receipt.receipt'),
    cashier: t('receipt.cashier'),
    customer: t('receipt.customer'),
    colItem: t('receipt.col_item'),
    colQty: t('receipt.col_qty'),
    colUnitPrice: t('receipt.col_unit_price'),
    colTotal: t('receipt.col_total'),
    subtotal: t('receipt.subtotal'),
    discount: t('receipt.discount'),
    tax: t('receipt.tax'),
    total: t('receipt.total'),
    paid: t('receipt.paid'),
    via: t('receipt.via'),
    balanceDue: t('receipt.balance_due'),
    thankYou: t('receipt.thank_you'),
    promoWas: t('receipt.promo_was'),
    debtRepayment: t('receipt.debt_repayment'),
    totalCollected: t('receipt.total_collected'),
    saleTitle: t('receipt.sale_title'),
    date: t('receipt.date'),
    paymentMethod: t('receipt.payment_method'),
    methodMixed: t('receipt.method_mixed'),
    paidStatus: t('receipt.paid_status'),
    amountPaid: t('receipt.amount_paid'),
    generatedBy: t('receipt.generated_by'),
    onlineReceipt: t('receipt.online_receipt'),
  }
}
